### ISSUE TITLE
Tokenizer task - "More information" link at VSTS opens up a 404 error page

### ISSUE THREAD

**Issue by akunaatrium** [TotalALM/VSTS-Tasks#13]
The URL that is opened is this:
https://github.com/TotalALM/VSTS-Tasks/blob/master/VSO%20Tasks/Tokenization/README.md

**Comment by KevinDMack** [comment]
Thanks for bringing this to our attention, and we will get it resolved.

**Comment by KevinDMack** [comment]
This was corrected in a build.
