### ISSUE TITLE
Sometimes the extension just does not load in the build pipeline

### ISSUE THREAD

**Issue by robsonalves** [TotalALM/VSTS-Tasks#18]
I'm using the extension in TFS 2015 OnPremisses in Build Vnext.
Sometimes when I edit a build definition, simply the tokenization step disappears, I go back and edit it and it resumes. 
I'd like you to run tests on that.

Thanks!

**Comment by KevinDMack** [comment]
That is on we haven't seen before.  But if I had to guess I would say check the following:
1.). When you install the extension it has to be installed at the collection level.  So if you have multiple collections the extension would not be available in all until you install it in all.

2.). Are you running TFS 2015 update 3?

3.). Is the extension always there when you run the build / release?  And it's only on edit that it seems to just not appear in the UI?

4.). Do you have any TFS logs you can share?  

5.). Is this happening for any other extensions you installed?

I gotta be honest this sounds like an issue with your TFS instance.

**Comment by KevinDMack** [comment]
Closing due to lack of information

**Comment by robsonalves** [comment]
Sorry about late.. I just forget it. This issue only happening with Tokenization Task.  Now I don't have log of tfs. My client use TFS 2015 update 3, I installed the task to make tokenization in our processes.  Sorry but I can't share more informations now :(

Maybe your declaration about problemas in tfs instance of my client, is right, their have a small infrastructure to provide tfs to all employe and it making a problem.

**Comment by KevinDMack** [comment]
Yeah unfortunately without more information there isn't much I can say, but I would recommend the above.
