### ISSUE TITLE
Archive Format incorrect for 7zip Archive task

### ISSUE THREAD

**Issue by pquinn80** [TotalALM/VSTS-Tasks#2]
It looks like the 7zip Archive task isn't handling the archive format correctly.  I've set my value to be "zip" but when the task executes it has a value of "AzureVMs".  When the PowerShell script is checking for the format on lines 44 & 46 it doesn't match and thus the task does nothing.  

![image](https://cloud.githubusercontent.com/assets/1643956/13933564/ca290528-ef7b-11e5-996d-a6384fa5fe3c.png)

**Comment by rohrerb** [comment]
Thank you for reporting this.  I will get this fixed in a few and push a update. :D

**Comment by rohrerb** [comment]
I just pushed a new package to the marketplace which should correct your error listed above.
