### ISSUE TITLE
UTF-8 file encoding not supported by Tokenization

### ISSUE THREAD

**Issue by KevinDMack** [TotalALM/VSTS-Tasks#24]
[From VSTS Marketplace]
Benjamin Abt
2/21/2017

Works fine but cannot handle UTF-8. We get a lot of encoding errors which makes this extension unusable for the most usecases. It's a pity.

**Comment by BenjaminAbt** [comment]
As I can see now after your issue here, my comment is in behalf of the same issue like #17

**Comment by rohrerb** [comment]
Resolved with the following commit.  https://github.com/TotalALM/VSTS-Tasks/commit/3a1eda4c6a653db538a0c85830e29d517c5e4a06

I will package this task and publish on the marketplace by EOD.
