### ISSUE TITLE
Critical Issue when token value contains $0

### ISSUE THREAD

**Issue by plraustin** [TotalALM/VSTS-Tasks#25]
Has been working great until one of our values contained $0  (dollarsign zero).   The component strangely substitutes the $0 in the replacement value with the token name.

Example:  __SampleToken__   val$0xyz

Results in:  val__SampleToken__xyz

Unfortunately this bug hit us on a production deployment because only the production environment had $0 in one of the environment values.

**Comment by KevinDMack** [comment]
This is a limitation with powershell and not something we can necessarily work around in a productive manner.
