### ISSUE TITLE
Running Chocolatey On Hosted Agent

### ISSUE THREAD

**Issue by russelldyas** [TotalALM/VSTS-Tasks#4]
I am trying to use Chocolatey extension on VSTS with a hosted agent.  However it reports back errors (mainly down to not having right permissions)  

`Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\Chocolatey\1.0.6\startChocolatey.ps1
Exception calling "SetInfo" with "0" argument(s): "Access is denied.
"
Exception setting "description": "Cannot set the Value property for PSMemberInfo object of type "System.Management.Automation.PSMethod"."
Exception calling "SetInfo" with "0" argument(s): "Access is denied.
"
Exception calling "add" with "1" argument(s): "A member could not be added to or removed from the local group because the member does not exist.
"
Access is denied. To run this cmdlet, start Windows PowerShell with the "Run as administrator" option.
Connecting to remote server TASKAGENT5-0014 failed with the following error message : The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.
Access is denied. To run this cmdlet, start Windows PowerShell with the "Run as administrator" option.
Exception calling "Delete" with "2" argument(s): "The user name could not be found.`

Can this run on a hosted agent in vsts

From

Russell

**Comment by rohrerb** [comment]
Russell,  Chocolatey will require your agent to be running as a administrator.  Hosted agents are not running in admin mode.  To you use this task you will need to have a agent running on a VM which is running with elevated privileges.

**Comment by russelldyas** [comment]
@rohrerb 

Thank you for the update.  That is a shame as trying to move away from our VM agents and I was hoping could use it to get 7zip on the hosted agent (to be able to use your 7zip tasks).  

Thank you for your quick response.
