### ISSUE TITLE
Running Chocolatey Remote PowerShell Error

### ISSUE THREAD

**Issue by russelldyas** [TotalALM/VSTS-Tasks#5]
Hello

Currently we are getting an error when using the task (on-premises agent).

Tried via vsts got an error to help with debugging I ran the PowerShell agent locally and still got the same issue. I also checked the firewall and this is disabled.

The error is:

: Access is denied. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (QA-W2K12-01:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionStateBroken
WARNING: Disabling the session configurations does not undo all the changes made by the Enable-PSRemoting or Enable-PSSessionConfiguration cmdlet. You might have to manua
lly undo the changes by following these steps:
    1. Stop and disable the WinRM service.
    2. Delete the listener that accepts requests on any IP address.
    3. Disable the firewall exceptions for WS-Management communications.
    4. Restore the value of the LocalAccountTokenFilterPolicy to 0, which restricts remote access to members of the Administrators group on the computer.

Logging From Script:

PS C:\agent\tasks\Chocolatey\1.0.6> C:\agent\tasks\Chocolatey\1.0.6\startChocolatey.ps1
cmdlet startChocolatey.ps1 at command pipeline position 1
Supply values for the following parameters:
packages: psexec
WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.
[QA-***_-01] Connecting to remote server QA-**__-01 failed with the following error message : Access is denied. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (QA-_**-01:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionStateBroken
WARNING: Disabling the session configurations does not undo all the changes made by the Enable-PSRemoting or Enable-PSSessionConfiguration cmdlet. You might have to manually undo the changes by following these steps:
    1. Stop and disable the WinRM service.
    2. Delete the listener that accepts requests on any IP address.
    3. Disable the firewall exceptions for WS-Management communications.
    4. Restore the value of the LocalAccountTokenFilterPolicy to 0, which restricts remote access to members of the Administrators group on the computer.

From

Russell

**Comment by KevinDMack** [comment]
Question for you, are you still having this error.  And does your firewall allow access to the Chocolatey service.

**Comment by KevinDMack** [comment]
Given no further response to quantify the issue.  Closing this item.
