### ISSUE TITLE
Sign in attempt prevented

### ISSUE THREAD

**Issue by ranjan-ranjan** [TotalALM/VSTS-Tasks#8]
I have given email settings of outlook and gmail in https://github.com/TotalALM/VSTS-Tasks/tree/master/Tasks/Email, but it was not able to send email. There should be other workaround for this. without asking for email & password.

**Comment by rohrerb** [comment]
So your looking to use a email task with smtp settings that don't require authentication?   Basically your looking to bounce your email off of a open relay?

**Comment by ranjan-ranjan** [comment]
yes. means without smtp server.

**Comment by KevinDMack** [comment]
But I guess trying to understand this further, if you are using outlook or gmail, you are going to get prompted, are you looking for an email service that will give you an open relay? without having to stand up an SMTP server?  If so I would recommend using SendGrid, it will allow you to set a username and password as part of the task without having to standup an SMTP server.

**Comment by ranjan-ranjan** [comment]
google and outlook find out that it is not getting logged in by a person. so it gets blocked. we get notifications in mailbox also

**Comment by KevinDMack** [comment]
Honestly then it sounds like your issues are with the email providers you are looking at and not the task.  Gmail and Outlook are not going to allow you to leverage an Open Relay, and you are going to need an SMTP server of some kind to send email, or a cloud based service like SendGrid, there's no way we can encapsulate a smtp server in the task.
